[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.11"
  NEXT_PUBLIC_EMAILJS_SERVICE_ID = "service_aq31ryq"
  NEXT_PUBLIC_EMAILJS_TEMPLATE_ID = "template_i6hf19e"
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY = "TVAPL6E8ACT_xqRDP"

[[plugins]]
  package = "@netlify/plugin-nextjs"
